### ISSUE TITLE
Update for sensor.potential_breaking_changes fails

### ISSUE THREAD

**Issue by Nicxe** [custom-components/breaking_changes#10] opened 2019-07-18 19:02 UTC
## Version of the custom_component
0.2.0

hass.io / 0.96

## Describe the bug
I have this in my log

```
Update for sensor.potential_breaking_changes fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 378, in async_device_update
    await self.async_update()
  File "/config/custom_components/breaking_changes/sensor.py", line 29, in async_update
    await update_data(self.hass)
  File "/config/custom_components/breaking_changes/__init__.py", line 95, in update_data
    await haversion.get_local_version()
AttributeError: 'Version' object has no attribute 'get_local_version'
```

and 

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/breaking_changes/__init__.py", line 77, in loaded_platforms
    hass, no_throttle=True
  File "/config/custom_components/breaking_changes/__init__.py", line 95, in update_data
    await haversion.get_local_version()
AttributeError: 'Version' object has no attribute 'get_local_version'
```

I have the sensor, don't know if it works but the sensor shows along my entities

**Comment by ludeeus** [comment] 2019-07-18 19:11
Duplicate of #9

**Closed as completed by ludeeus** 2019-07-18 19:11 UTC
